### ISSUE TITLE
No need for ...

### ISSUE THREAD

**Issue by AaronGulman** [pavithrakumar22/DomoticAI#1]
Hi,
I just popped up here to quickly point out that you should not / do not have to commit your `node_modules` just create a `.gitignore` in the root of your repo and add `node_modules` to it.

When your `node_modules` dir is committed it does nothing but bloats the size of your repo . Simply delete it (merge with my changes preferably  haha) and then clone the repo , make sure your `.gitignore` includes `node_modules` in it then run `npm install` once you `cd` into the your target part of the project(frontend/backend) so the dependencies could be installed and your IDE /text editor with integrated `Git` won't insist on committing your `node_modules` .

Great job btw and good luck !

**Comment by pavithrakumar22** [comment]
ThankYou @AaronGulman for your suggestion.Actually this is a team project and we are facing a lot of issues due to the dependencies so we thought after completion of the project we will add a .gitignore file and close it.
Still Thankyou for poiniting it out and have a great day!
