### ISSUE TITLE
Sensetive data

### ISSUE THREAD

**Issue by AaronGulman** [pavithrakumar22/DomoticAI#3]
Hi,
So it's me again with another one of these:

I have noticed your `.env `being committed and even taking into considering the things you mentioned in the previous issue , I would like to mentioned that I am able to manipulate data in your DB right now and adjust anything I want (as a Game of Thrones fan I have a particular appreciation of the provided data haha)

But yes , better hide it even if you are just in the development process and you're simply using some dummy data since some bad actors can  mess up  your data which can in turn make things less productive for y'all.

Just don't commit your `.env`(s) . 

Have fun with the project !

**Comment by pavithrakumar22** [comment]
Ya sure we will take care of it
